export const defaultStyles = {
  point_color: '#ff7800',
  point_size: 8,
  point_opacity: 1.0,
  point_icon_type: 'marker',
  point_label_size: 12,
  point_label_color: '#000000',
  line_color: '#ff7800',
  line_width: 2,
  line_opacity: 0.8,
  line_style: 'solid',
  polygon_fill_color: '#ff7800',
  polygon_fill_opacity: 0.3,
  polygon_stroke_color: '#ff7800',
  polygon_stroke_width: 2,
  polygon_stroke_style: 'solid',
};
