services:
  mymap:
    image: mymap:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mymap
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3002
      - DB_PATH=/app/server/data/panorama_map.db
      - UPLOAD_DIR=uploads
      - MAX_FILE_SIZE=52428800
      - LOG_LEVEL=info
    volumes:
      - mymap_data:/app/server/data
      - mymap_uploads:/app/server/uploads
      - mymap_logs:/app/server/logs
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3002/api/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

  nginx:
    image: nginx:1.25-alpine
    container_name: mymap-nginx
    restart: unless-stopped
    depends_on:
      mymap:
        condition: service_healthy
    ports:
      - "50000:50000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mymap_data:
  mymap_uploads:
  mymap_logs:


